name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy the correct config file based on branch
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          cp config_production.json config.json
        elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
          cp config_develop.json config.json
        else
          cp config_develop.json config.json
        fi

    - name: Set environment variables
      run: ./set_env_vars.sh

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt -t ./package; fi

    - name: Package code
      run: |
        rsync -r --exclude=package . ./package/
        cd package
        zip -r ../function.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://function.zip | jq 'del(.Environment)' | cat